### PR TITLE
add option to hide zero-counter rows

### PR DESCRIPTION
**Pull request by svensven**
Hi, just something I added to make my rules easier to watch.

### CODE REVIEW

**Comment by flyingrhinonz** [comment]
Thanks for the addition.
Let me check that the display doesn't corrupt when zero packets rules become non zero later on. I'll then merge the pull request.

**Comment by flyingrhinonz** [comment]
Merge to testing branch

**Comment by flyingrhinonz** [comment]
Flipping from show-zeros to hide-zeros will give a partial or blank screen - depending upon the number of lines that get hidden. This limitation/bug is a consequence of this pull request.
Workaround is to scroll up or jump to top of screen with one of the keyboard shortcuts.

**Comment by svensven** [comment]
Huh, hiding zeros works perfectly for me. The only artifact I get is one interval of duplicated numbers when _showing_ zeros again.

**Comment by svensven** [comment]
Ohh, now I get it, if I scroll down beyond where the filtered view has rows to display.

**Pull request merged**
